### ISSUE TITLE
Multiple icons when post new reply

### ISSUE THREAD

**Issue by jiangcaiyang** [0312birdzhang/nodebb-plugin-share-post-icons-cn#2]
Please help check the code, hope to resolve.

**Comment by 0312birdzhang** [comment]
Try this https://github.com/0312birdzhang/nodebb-plugin-share-post-icons-cn/pull/3

**Comment by 0312birdzhang** [comment]
https://github.com/0312birdzhang/nodebb-plugin-share-post-icons-cn/pull/3 应该是修复了，关闭了
